# -*- coding: utf-8 -*-
"""Latihan Fungsi 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AsLZjlmxq5fO09p6LhuWQGg1Tt1XFL-a
"""

#Mengembangkan fungsi agar dapat menghitung besaran penghasilan pegawai
def penghasilan_pegawai():
    kategori = input("Kategori Pegawai (Tetap/ Kontrak): ")
    lembur = float(input("Berapa jam lembur: "))
    if kategori == 'Tetap' or kategori == 'tetap':
        if lembur >0 and lembur <= 20:
            penghasilan = 4500000 + (lembur*50000)
        elif lembur > 20:
            penghasilan = 4500000 + (20*50000)
            print(f'Penghasilan Anda bulan ini adalah: Rp {penghasilan}')
        else:
            print('Jam Lembur tidak boleh negatif')
    elif kategori == 'Kontrak' or kategori == 'kontrak':
        if lembur > 0 and lembur <= 20:
            penghasilanKon = (4500000*0.7)+(lembur*30000)
        elif lembur > 20:
            penghasilanKon = (4500000*0.7)+(20*30000)
            print(f'Penghasilan Anda bulan ini adalah: Rp {penghasilanKon}')
        else:
            print('Jam Lembur tidak boleh negatif')
    else:
        print('Kategori yang Anda masukkan salah')

penghasilan_pegawai()

#Mengembangkan fungsi agar dapat menghitung besaran penghasilan pegawai
def penghasilan_pegawai():
    kategori = input("Kategori Pegawai (Tetap/ Kontrak): ")
    lembur = float(input("Berapa jam lembur: "))
    if kategori == 'Tetap' or kategori == 'tetap':
        if lembur >0 and lembur <= 20:
            penghasilan = 4500000 + (lembur*50000)
            penghasilanAkhir = penghasilan - (penghasilan*0.01)
            print(f'Penghasilan Anda bulan ini adalah: Rp {penghasilanAkhir}')
        elif lembur > 20:
            penghasilan = 4500000 + (20*50000)
            penghasilanAkhir = penghasilan - (penghasilan*0.01)
            print(f'Penghasilan Anda bulan ini adalah: Rp {penghasilanAkhir}')
        else:
            print('Jam Lembur tidak boleh negatif')
    elif kategori == 'Kontrak' or kategori == 'kontrak':
        if lembur > 0 and lembur <= 20:
            penghasilanKon = (4500000*0.7)+(lembur*30000)
            penghasilanKonAkhir = penghasilanKon - (penghasilanKon*0.01)
            print(f'Penghasilan Anda bulan ini adalah: Rp {penghasilanKonAkhir}')
        elif lembur > 20:
            penghasilanKon = (4500000*0.7)+(20*30000)
            penghasilanKonAkhir = penghasilanKon - (penghasilanKon*0.01)
            print(f'Penghasilan Anda bulan ini adalah: Rp {penghasilanKonAkhir}')
        else:
            print('Jam Lembur tidak boleh negatif')
    else:
        print('Kategori yang Anda masukkan salah')

penghasilan_pegawai()

#membuat list
nilai = [10, 8, 6, 4, 2, 0, -2, -4]

#tampilkan list
nilai

def harga_promo(*harga):
    pembayaran = sum(harga) 
    total_diskon = pembayaran * 0.45
    total_bayar = int(pembayaran - total_diskon)
    return total_bayar

print('Harga akhir yang dibayarkan: ')
harga_promo(200000, 300000, 400000, 500000,600000, 700000)

def daftar_pegawai(**pegawai):
  for nama, kota in pegawai.items():
    print(f'{nama} berasal dari kota {kota}')

daftar_pegawai(Irsyaad = "Bekasi", Chaidar = "Ternate", Dwita = "Bali", Fikria = "Malang", Nurhaliza = "Yogyakarta")